-- Machine Checklist module (ported from the Spring service). People live in user_db, so *_id columns that
-- point at a person / department are plain BIGINTs (no foreign key across databases).

-- The first scaffold of this database (never used) is dropped when it is empty.
DO $$ DECLARE t TEXT; n BIGINT;
BEGIN
    FOREACH t IN ARRAY ARRAY['inspection_answers','inspections','checklist_items','checklists','maintenance','machines'] LOOP
        IF to_regclass('public.'||t) IS NOT NULL THEN
            EXECUTE format('SELECT count(*) FROM %I', t) INTO n;
            IF n = 0 THEN EXECUTE format('DROP TABLE %I CASCADE', t); END IF;
        END IF;
    END LOOP;
END $$;

CREATE TABLE IF NOT EXISTS machine_type (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    machine_group_id   VARCHAR(10)  NOT NULL,
    machine_group_name VARCHAR(160) NOT NULL,
    machine_type_id    VARCHAR(10)  NOT NULL,
    machine_type_name  VARCHAR(160) NOT NULL,
    status             VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    created_by BIGINT, updated_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), deleted_at TIMESTAMPTZ,
    UNIQUE (machine_group_id, machine_type_id)
);

CREATE TABLE IF NOT EXISTS question (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    detail      VARCHAR(255) NOT NULL,
    description TEXT,
    is_choice   BOOLEAN      NOT NULL DEFAULT TRUE,      -- TRUE = OK / NG answer, FALSE = free text / number
    created_by BIGINT, updated_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), deleted_at TIMESTAMPTZ
);
CREATE UNIQUE INDEX IF NOT EXISTS question_detail_unique ON question (lower(detail)) WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS register_request (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    machine_name         VARCHAR(200),
    brand                VARCHAR(120),
    model                VARCHAR(120),
    serial_number        VARCHAR(120),
    price                NUMERIC(14,2),
    quantity             INTEGER,
    watt                 INTEGER,
    horse_power          INTEGER,
    department_id        BIGINT NOT NULL,
    responsible_id       BIGINT,
    supervisor_id        BIGINT,
    manager_id           BIGINT,
    note                 TEXT,
    attachment           TEXT,          -- JSON list of file names
    work_instruction     TEXT,          -- JSON list of file names
    maintenance          TEXT,          -- JSON plan: [{"round":1,"due_date":"2026-03-01"}]
    calibration          TEXT,          -- JSON plan: [{"due_date":"2026-03-01"}]
    has_warranty         VARCHAR(5),
    warranty_note        TEXT,
    warranty_expire_date DATE,
    warranty_files       TEXT,
    is_new               BOOLEAN,
    created_by BIGINT, updated_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), deleted_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS machine (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    machine_code            VARCHAR(40) NOT NULL UNIQUE,
    machine_name            VARCHAR(200) NOT NULL,
    machine_group_id        VARCHAR(10),
    machine_type_id         VARCHAR(10),
    machine_status          VARCHAR(30) NOT NULL DEFAULT 'OPERATIONAL',      -- OPERATIONAL | UNDER MAINTENANCE | SCRAPPED | CANCELLED
    check_status            VARCHAR(30) NOT NULL DEFAULT 'PENDING',          -- PENDING | PENDING SUPERVISOR | PENDING MANAGER | COMPLETED | OUT OF SERVICE
    model                   VARCHAR(120),
    brand                   VARCHAR(120),
    serial_number           VARCHAR(120),
    machine_number          VARCHAR(60),
    department_id           BIGINT,
    register_id             BIGINT,
    register_date           DATE,
    cancel_date             DATE,
    reason_cancel           TEXT,
    is_calibration          BOOLEAN NOT NULL DEFAULT FALSE,
    certificate_period      VARCHAR(20),
    maintenance_period      VARCHAR(20),
    reset_period            VARCHAR(10) NOT NULL DEFAULT 'WEEKLY',          -- WEEKLY | MONTHLY: how often the responsible person re-checks
    image                   VARCHAR(255),
    responsible_person_id   BIGINT,
    responsible_person_name VARCHAR(160),
    supervisor_id           BIGINT,
    manager_id              BIGINT,
    work_instruction        TEXT,
    qr_code                 TEXT,
    note                    TEXT,
    last_review             DATE,
    review_by               VARCHAR(160),
    has_warranty            VARCHAR(5),
    warranty_note           TEXT,
    warranty_expire_date    DATE,
    warranty_files          TEXT,
    is_new                  BOOLEAN,
    created_by BIGINT, updated_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), deleted_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS machine_dept_idx ON machine (department_id);
CREATE INDEX IF NOT EXISTS machine_resp_idx ON machine (responsible_person_id);

-- Checklist items of a machine. reset_time is a cron-style day rule "0 0 0 <day-of-month> * <day-of-week>":
--   '0 0 0 * * 1' = general check (done at every use),  '0 0 0 * * *' = daily,  '0 0 0 1 * *' = monthly …
CREATE TABLE IF NOT EXISTS machine_checklist (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    machine_code VARCHAR(40) NOT NULL,
    question_id  BIGINT NOT NULL REFERENCES question(id),
    check_status BOOLEAN NOT NULL DEFAULT FALSE,
    reset_time   VARCHAR(40) NOT NULL DEFAULT '0 0 0 * * 1',
    created_by BIGINT, updated_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (machine_code, question_id, reset_time)
);
CREATE INDEX IF NOT EXISTS machine_checklist_code_idx ON machine_checklist (machine_code);

CREATE TABLE IF NOT EXISTS maintenance_checklist (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    machine_code VARCHAR(40) NOT NULL,
    question_id  BIGINT NOT NULL REFERENCES question(id),
    check_status BOOLEAN NOT NULL DEFAULT FALSE,
    reset_time   VARCHAR(40),
    created_by BIGINT, updated_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (machine_code, question_id)
);

CREATE TABLE IF NOT EXISTS checklist_record (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    check_type              VARCHAR(20) NOT NULL DEFAULT 'GENERAL',          -- GENERAL | MAINTENANCE
    recheck                 BOOLEAN NOT NULL DEFAULT FALSE,                  -- TRUE = the responsible person's periodic re-check (goes to approval)
    machine_code            VARCHAR(40) NOT NULL,
    machine_name            VARCHAR(200),
    machine_status          VARCHAR(30),
    machine_checklist       TEXT,       -- JSON answers: [{"id":1,"question_id":3,"detail":"…","answer":"OK|NG|text","remark":""}]
    machine_note            TEXT,
    image                   VARCHAR(255),
    user_id                 VARCHAR(190),
    user_name               VARCHAR(160),
    supervisor              BIGINT,
    date_supervisor_checked TIMESTAMPTZ,
    manager                 BIGINT,
    date_manager_checked    TIMESTAMPTZ,
    checklist_status        VARCHAR(40) NOT NULL DEFAULT 'COMPLETED',        -- COMPLETED | PENDING SUPERVISOR | PENDING MANAGER | …-OVERDUE | REJECTED
    reason_not_checked      TEXT,
    job_detail              TEXT,
    created_by BIGINT, updated_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS checklist_record_code_idx ON checklist_record (machine_code, created_at);
CREATE INDEX IF NOT EXISTS checklist_record_status_idx ON checklist_record (checklist_status);

CREATE TABLE IF NOT EXISTS maintenance_record (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    machine_code            VARCHAR(40) NOT NULL,
    machine_name            VARCHAR(200),
    years                   VARCHAR(4) NOT NULL,
    round                   INTEGER,
    due_date                DATE,
    plan_date               DATE,
    start_date              DATE,
    actual_date             DATE,
    status                  VARCHAR(30),                                     -- NULL = planned | COMPLETED | COMPLETED (LATE)
    maintenance_by          VARCHAR(20),                                     -- INTERNAL | EXTERNAL
    responsible_maintenance BIGINT,
    note                    TEXT,
    attachment              TEXT,
    maintenance_type        VARCHAR(20) NOT NULL DEFAULT 'PREVENTIVE',
    checklist_record_id     BIGINT,
    is_canceled             BOOLEAN NOT NULL DEFAULT FALSE,
    canceled_at             DATE,
    created_by BIGINT, updated_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS maintenance_record_code_idx ON maintenance_record (machine_code, years);

CREATE TABLE IF NOT EXISTS calibration_record (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    machine_code         VARCHAR(40) NOT NULL,
    machine_name         VARCHAR(200),
    years                VARCHAR(4) NOT NULL,
    due_date             DATE,
    start_date           DATE,
    certificate_date     DATE,
    results              VARCHAR(20),                                         -- PASS | FAILED
    criteria             TEXT,
    measuring_range      TEXT,
    accuracy             TEXT,
    calibration_range    TEXT,
    calibration_status   VARCHAR(30),
    attachment           TEXT,
    note                 TEXT,
    permissible_capacity TEXT,
    comment              TEXT,
    resolution           TEXT,
    max_uncertainty      TEXT,
    mpe                  TEXT,
    check_mpe            VARCHAR(20),
    check_resolution     VARCHAR(20),
    check_result         VARCHAR(20),
    reason_not_pass      TEXT,
    is_canceled          BOOLEAN NOT NULL DEFAULT FALSE,
    canceled_at          DATE,
    created_by BIGINT, updated_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS calibration_record_code_idx ON calibration_record (machine_code, years);

CREATE TABLE IF NOT EXISTS responsible_history (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    machine_code          VARCHAR(40) NOT NULL,
    responsible_person_id BIGINT NOT NULL,
    effective_from        DATE NOT NULL,
    effective_to          DATE
);
CREATE INDEX IF NOT EXISTS responsible_history_code_idx ON responsible_history (machine_code);

-- Small key/value state for the background jobs (last run of each).
CREATE TABLE IF NOT EXISTS job_state (
    key VARCHAR(80) PRIMARY KEY, value TEXT, updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
