-- Projects with tasks, and the history of who a record belonged to before it was reassigned.

CREATE TABLE IF NOT EXISTS projects (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code          VARCHAR(30) UNIQUE,
    name          VARCHAR(200) NOT NULL,
    description   TEXT,
    status        VARCHAR(20) NOT NULL DEFAULT 'PLANNING',   -- PLANNING | ACTIVE | ON_HOLD | DONE | CANCELLED
    start_date    DATE,
    end_date      DATE,
    owner_id      BIGINT,
    department_id BIGINT,
    created_by BIGINT, updated_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS projects_department_idx ON projects (department_id);
CREATE INDEX IF NOT EXISTS projects_status_idx ON projects (status);

-- People responsible for a project (many)
CREATE TABLE IF NOT EXISTS project_members (
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    user_id    BIGINT NOT NULL,
    added_by   BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (project_id, user_id)
);
CREATE INDEX IF NOT EXISTS project_members_user_idx ON project_members (user_id);

CREATE TABLE IF NOT EXISTS tasks (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code          VARCHAR(30) UNIQUE,
    project_id    BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    name          VARCHAR(200) NOT NULL,
    description   TEXT,
    status        VARCHAR(20) NOT NULL DEFAULT 'TODO',       -- TODO | IN_PROGRESS | BLOCKED | DONE | CANCELLED
    start_date    DATE,
    end_date      DATE,
    owner_id      BIGINT,
    department_id BIGINT,
    created_by BIGINT, updated_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS tasks_project_idx ON tasks (project_id);
CREATE INDEX IF NOT EXISTS tasks_status_idx ON tasks (status);

-- People responsible for a task (many)
CREATE TABLE IF NOT EXISTS task_assignees (
    task_id    BIGINT NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
    user_id    BIGINT NOT NULL,
    added_by   BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (task_id, user_id)
);
CREATE INDEX IF NOT EXISTS task_assignees_user_idx ON task_assignees (user_id);

-- Who a record (or a project / task responsibility) belonged to before it was handed over
CREATE TABLE IF NOT EXISTS ownership_history (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type  VARCHAR(20) NOT NULL,
    entity_id    BIGINT NOT NULL,
    role         VARCHAR(12) NOT NULL DEFAULT 'owner',      -- owner | responsible
    from_user_id BIGINT,
    to_user_id   BIGINT,
    changed_by   BIGINT,
    note         VARCHAR(255),
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ownership_history_entity_idx ON ownership_history (entity_type, entity_id);
CREATE INDEX IF NOT EXISTS ownership_history_from_idx ON ownership_history (from_user_id);

-- Saved column mappings for the admin import tool
CREATE TABLE IF NOT EXISTS import_mappings (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(120) NOT NULL,
    target     VARCHAR(40) NOT NULL,
    mapping    TEXT NOT NULL,                               -- JSON: {"Excel header": "column"}
    created_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
