-- Opportunity stage colours and which stages each department may use, yearly sales targets, reminder tracking.

-- The stage list itself is fixed (it matches the OpportunityStage enum); only the colour is a setting.
CREATE TABLE IF NOT EXISTS crm_stages (
    code  VARCHAR(30) PRIMARY KEY,
    color VARCHAR(9) NOT NULL,
    sort  SMALLINT NOT NULL
);
INSERT INTO crm_stages (code, color, sort) VALUES
  ('QUALIFICATION',      '#0ea5e9', 1),
  ('SURVEY_PROPOSAL',    '#8b5cf6', 2),
  ('EVALUATION_TESTING', '#f59e0b', 3),
  ('NEGOTIATION',        '#ea580c', 4),
  ('CLOSED_WON',         '#16a34a', 5),
  ('CLOSED_LOST',        '#dc2626', 6),
  ('ON_HOLD',            '#64748b', 7),
  ('CANCEL',             '#94a3b8', 8)
ON CONFLICT (code) DO NOTHING;

-- A row here means "this department does NOT use this stage". No row = available (the default).
CREATE TABLE IF NOT EXISTS stage_hidden (
    stage         VARCHAR(30) NOT NULL REFERENCES crm_stages(code) ON DELETE CASCADE,
    department_id BIGINT NOT NULL,
    updated_by    BIGINT,
    PRIMARY KEY (stage, department_id)
);

-- One row per department and year: targets per quarter + total, and the actuals saved for that year.
CREATE TABLE IF NOT EXISTS sales_targets (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id BIGINT   NOT NULL,
    year          SMALLINT NOT NULL,
    q1 NUMERIC(16,2) NOT NULL DEFAULT 0, q2 NUMERIC(16,2) NOT NULL DEFAULT 0, q3 NUMERIC(16,2) NOT NULL DEFAULT 0, q4 NUMERIC(16,2) NOT NULL DEFAULT 0,
    total NUMERIC(16,2) NOT NULL DEFAULT 0,
    a1 NUMERIC(16,2), a2 NUMERIC(16,2), a3 NUMERIC(16,2), a4 NUMERIC(16,2),        -- saved actuals (NULL = not saved yet)
    actuals_saved_at TIMESTAMPTZ,
    actuals_saved_by BIGINT,
    created_by BIGINT, updated_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (department_id, year)
);

-- Reminder e-mail / bell already sent for this activity?
ALTER TABLE activities ADD COLUMN IF NOT EXISTS reminder_sent_at TIMESTAMPTZ;
