-- =====================================================================
--  CRM module schema. Column names follow the Java entities
--  (Lead, Contact, Opportunity, Campaign, Activity, Industry, LeadSource).
--  A "lead" is the company / account; contacts are people at a lead.
--  owner_id / department_id / *_by hold user_db ids (no cross-database FK).
-- =====================================================================

-- The first CRM draft (customers / contacts / leads / opportunities) had no screens.
-- Replace it, but never throw data away.
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = current_schema() AND table_name = 'leads' AND column_name = 'title') THEN
        IF (SELECT count(*) FROM leads) + (SELECT count(*) FROM customers) + (SELECT count(*) FROM opportunities) + (SELECT count(*) FROM contacts) > 0 THEN
            RAISE EXCEPTION 'crm_db still holds rows in the old CRM draft tables; export them, empty the tables and reload the page.';
        END IF;
        DROP TABLE IF EXISTS opportunities, contacts, leads, customers CASCADE;
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS industries (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(120) NOT NULL UNIQUE,
    color      VARCHAR(9)   NOT NULL DEFAULT '#5b616b',
    created_by BIGINT, updated_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS lead_sources (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(120) NOT NULL UNIQUE,
    color      VARCHAR(9)   NOT NULL DEFAULT '#5b616b',
    created_by BIGINT, updated_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- rate_to_base: how many base-currency units one unit of this currency is worth (dashboard totals)
CREATE TABLE IF NOT EXISTS currencies (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code         VARCHAR(3)  NOT NULL UNIQUE,
    name         VARCHAR(60) NOT NULL,
    rate_to_base NUMERIC(18,6) NOT NULL DEFAULT 1 CHECK (rate_to_base > 0),
    is_base      BOOLEAN NOT NULL DEFAULT FALSE,
    created_by BIGINT, updated_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Registered products. Products that are not registered are typed free-text on the opportunity.
CREATE TABLE IF NOT EXISTS products (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(40) UNIQUE,
    name        VARCHAR(200) NOT NULL,
    unit        VARCHAR(30),
    unit_price  NUMERIC(16,2),
    currency    VARCHAR(3) NOT NULL DEFAULT 'THB',
    description TEXT,
    is_active   BOOLEAN NOT NULL DEFAULT TRUE,
    created_by BIGINT, updated_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS leads (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code          VARCHAR(30) UNIQUE,
    name_en       VARCHAR(200) NOT NULL,
    name_th       VARCHAR(200),
    tax_id        VARCHAR(30),
    revenue       NUMERIC(18,2),
    phone         VARCHAR(40),
    mobile        VARCHAR(40),
    fax           VARCHAR(40),
    address       TEXT,
    city          VARCHAR(80),
    province      VARCHAR(80),
    country       VARCHAR(80),
    zipcode       VARCHAR(20),
    description   TEXT,
    image         VARCHAR(255),
    is_register   BOOLEAN NOT NULL DEFAULT FALSE,
    is_government BOOLEAN NOT NULL DEFAULT FALSE,
    company_id    BIGINT REFERENCES leads(id) ON DELETE SET NULL,   -- parent company
    owner_id      BIGINT,
    department_id BIGINT,
    created_by BIGINT, updated_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS leads_department_idx ON leads (department_id);
CREATE INDEX IF NOT EXISTS leads_owner_idx ON leads (owner_id);

CREATE TABLE IF NOT EXISTS lead_industries (
    lead_id     BIGINT NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
    industry_id BIGINT NOT NULL REFERENCES industries(id) ON DELETE CASCADE,
    PRIMARY KEY (lead_id, industry_id)
);
CREATE TABLE IF NOT EXISTS lead_lead_sources (
    lead_id        BIGINT NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
    lead_source_id BIGINT NOT NULL REFERENCES lead_sources(id) ON DELETE CASCADE,
    PRIMARY KEY (lead_id, lead_source_id)
);

CREATE TABLE IF NOT EXISTS contacts (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code               VARCHAR(30) UNIQUE,
    salutation         VARCHAR(20),
    name_en            VARCHAR(160) NOT NULL,
    name_th            VARCHAR(160),
    phone              VARCHAR(40),
    phone_ext          VARCHAR(10),
    fax                VARCHAR(40),
    email              VARCHAR(190),
    job_title          VARCHAR(120),
    department         VARCHAR(120),            -- department at the contact's own company
    description        TEXT,
    lead_source_id     BIGINT REFERENCES lead_sources(id) ON DELETE SET NULL,
    lead_id            BIGINT REFERENCES leads(id) ON DELETE SET NULL,
    avatar             VARCHAR(255),
    address            TEXT,
    city               VARCHAR(80),
    province           VARCHAR(80),
    country            VARCHAR(80),
    zipcode            VARCHAR(20),
    additional_contact TEXT,
    owner_id      BIGINT,
    department_id BIGINT,
    created_by BIGINT, updated_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS contacts_lead_idx ON contacts (lead_id);
CREATE INDEX IF NOT EXISTS contacts_department_idx ON contacts (department_id);

-- A contact can have many mobile numbers
CREATE TABLE IF NOT EXISTS contact_mobiles (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_id BIGINT NOT NULL REFERENCES contacts(id) ON DELETE CASCADE,
    number     VARCHAR(40) NOT NULL,
    ext        VARCHAR(10),
    label      VARCHAR(30),
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    sort       SMALLINT NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS contact_mobiles_contact_idx ON contact_mobiles (contact_id);

CREATE TABLE IF NOT EXISTS campaigns (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                   VARCHAR(30) UNIQUE,
    name                   VARCHAR(200) NOT NULL,
    type                   VARCHAR(30),
    status                 VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    start_date             TIMESTAMPTZ,
    end_date               TIMESTAMPTZ,
    budget                 NUMERIC(16,2),
    actual_cost            NUMERIC(16,2),
    expected_revenue       NUMERIC(16,2),
    expected_response_rate NUMERIC(5,2),
    actual_response_rate   NUMERIC(5,2),
    description            TEXT,
    owner_id      BIGINT,
    department_id BIGINT,
    created_by BIGINT, updated_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS campaigns_department_idx ON campaigns (department_id);

CREATE TABLE IF NOT EXISTS opportunities (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code              VARCHAR(30) UNIQUE,
    name              VARCHAR(200) NOT NULL,
    probability       NUMERIC(5,2),
    amount            NUMERIC(16,2),
    follow_at         TIMESTAMPTZ,
    close_at          TIMESTAMPTZ,
    currency          VARCHAR(3) NOT NULL DEFAULT 'THB',
    cancel_reason     TEXT,
    description       TEXT,
    priority          VARCHAR(10) NOT NULL DEFAULT 'MEDIUM',
    opportunity_stage VARCHAR(30) NOT NULL DEFAULT 'QUALIFICATION',
    lead_id           BIGINT REFERENCES leads(id) ON DELETE SET NULL,
    contact_id        BIGINT REFERENCES contacts(id) ON DELETE SET NULL,
    owner_id      BIGINT,
    department_id BIGINT,
    created_by BIGINT, updated_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS opportunities_department_idx ON opportunities (department_id);
CREATE INDEX IF NOT EXISTS opportunities_stage_idx ON opportunities (opportunity_stage);
CREATE INDEX IF NOT EXISTS opportunities_lead_idx ON opportunities (lead_id);

-- Registered products (product_id) or "other" products typed by hand (product_id NULL, name = what the customer asked for)
CREATE TABLE IF NOT EXISTS opportunity_products (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    opportunity_id BIGINT NOT NULL REFERENCES opportunities(id) ON DELETE CASCADE,
    product_id     BIGINT REFERENCES products(id) ON DELETE SET NULL,
    name           VARCHAR(200) NOT NULL,
    quantity       NUMERIC(14,2) NOT NULL DEFAULT 1,
    unit_price     NUMERIC(16,2),
    note           VARCHAR(255),
    sort           SMALLINT NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS opportunity_products_opp_idx ON opportunity_products (opportunity_id);

-- History of an opportunity: what was done in each stage and what comes next.
--   kind 'stage' = the opportunity moved to a stage (written automatically)
--   kind 'step'  = a next step someone planned (open until marked done)
CREATE TABLE IF NOT EXISTS opportunity_steps (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    opportunity_id BIGINT NOT NULL REFERENCES opportunities(id) ON DELETE CASCADE,
    kind           VARCHAR(10) NOT NULL DEFAULT 'step' CHECK (kind IN ('stage','step')),
    stage          VARCHAR(30) NOT NULL,                  -- stage the opportunity was in / moved to
    from_stage     VARCHAR(30),                           -- for kind 'stage': where it came from (NULL = created)
    title          VARCHAR(200) NOT NULL DEFAULT '',
    note           TEXT,
    due_at         TIMESTAMPTZ,
    is_done        BOOLEAN NOT NULL DEFAULT FALSE,
    done_at        TIMESTAMPTZ,
    done_by        BIGINT,
    created_by     BIGINT,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS opportunity_steps_opp_idx ON opportunity_steps (opportunity_id, created_at);

CREATE TABLE IF NOT EXISTS activities (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code             VARCHAR(30) UNIQUE,
    activity_type    VARCHAR(20) NOT NULL DEFAULT 'CALL',
    topic            VARCHAR(200) NOT NULL,
    status           VARCHAR(20) NOT NULL DEFAULT 'PLANNED',   -- PLANNED | DONE | CANCELLED (also replaces meeting_status)
    call_duration    INTEGER,                                   -- minutes
    call_direction   VARCHAR(10),
    meeting_duration INTEGER,                                   -- minutes
    meeting_type     VARCHAR(20),
    meeting_location VARCHAR(255),
    start_at         TIMESTAMPTZ,
    description      TEXT,
    lead_id          BIGINT REFERENCES leads(id) ON DELETE SET NULL,
    contact_id       BIGINT REFERENCES contacts(id) ON DELETE SET NULL,
    opportunity_id   BIGINT REFERENCES opportunities(id) ON DELETE SET NULL,
    notify_me        BOOLEAN NOT NULL DEFAULT FALSE,
    notify_before    INTEGER NOT NULL DEFAULT 0,                -- minutes before start_at
    owner_id      BIGINT,
    department_id BIGINT,
    created_by BIGINT, updated_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS activities_department_idx ON activities (department_id);
CREATE INDEX IF NOT EXISTS activities_start_idx ON activities (start_at);
CREATE INDEX IF NOT EXISTS activities_lead_idx ON activities (lead_id);
CREATE INDEX IF NOT EXISTS activities_contact_idx ON activities (contact_id);
CREATE INDEX IF NOT EXISTS activities_opportunity_idx ON activities (opportunity_id);

-- Comments (shown on activities and opportunities)
CREATE TABLE IF NOT EXISTS comments (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type VARCHAR(20) NOT NULL,
    entity_id   BIGINT NOT NULL,
    body        TEXT NOT NULL,
    created_by  BIGINT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS comments_entity_idx ON comments (entity_type, entity_id);

-- Files (stored outside the web root, downloaded through a permission check)
CREATE TABLE IF NOT EXISTS attachments (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type   VARCHAR(20) NOT NULL,
    entity_id     BIGINT NOT NULL,
    original_name VARCHAR(255) NOT NULL,
    stored_name   VARCHAR(80)  NOT NULL UNIQUE,
    mime          VARCHAR(120),
    size          BIGINT NOT NULL DEFAULT 0,
    uploaded_by   BIGINT,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS attachments_entity_idx ON attachments (entity_type, entity_id);

-- Extra people / departments who may open (or edit) a record besides its own department
CREATE TABLE IF NOT EXISTS record_shares (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type VARCHAR(20) NOT NULL,
    entity_id   BIGINT NOT NULL,
    target_type VARCHAR(12) NOT NULL CHECK (target_type IN ('user','department')),
    target_id   BIGINT NOT NULL,
    access      VARCHAR(6)  NOT NULL DEFAULT 'view' CHECK (access IN ('view','edit')),
    shared_by   BIGINT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (entity_type, entity_id, target_type, target_id)
);
CREATE INDEX IF NOT EXISTS record_shares_target_idx ON record_shares (target_type, target_id);

-- ---------------------------------------------------------------- lookup data
INSERT INTO industries (name, color) VALUES
  ('Manufacturing', '#2a78d6'), ('Food & Beverage', '#eb6834'), ('Automotive', '#4a3aa7'), ('Electronics', '#1baf7a'),
  ('Construction', '#eda100'), ('Energy & Utilities', '#008300'), ('Logistics', '#e87ba4'), ('Retail', '#e34948'),
  ('Healthcare', '#0b7a8a'), ('Government', '#5b616b')
ON CONFLICT (name) DO NOTHING;

INSERT INTO lead_sources (name, color) VALUES
  ('Website', '#2a78d6'), ('Referral', '#1baf7a'), ('Trade show', '#eb6834'), ('Cold call', '#5b616b'),
  ('E-mail campaign', '#4a3aa7'), ('Social media', '#e87ba4'), ('Existing customer', '#008300'), ('Partner', '#eda100')
ON CONFLICT (name) DO NOTHING;

-- Approximate rates: change them in CRM → Settings → Currencies.
INSERT INTO currencies (code, name, rate_to_base, is_base) VALUES
  ('THB', 'Thai baht', 1, TRUE), ('USD', 'US dollar', 35, FALSE), ('EUR', 'Euro', 38, FALSE),
  ('JPY', 'Japanese yen', 0.24, FALSE), ('CNY', 'Chinese yuan', 4.9, FALSE), ('SGD', 'Singapore dollar', 26, FALSE),
  ('LKR', 'Sri Lankan rupee', 0.11, FALSE)
ON CONFLICT (code) DO NOTHING;
