-- The seller (our company): used on every e-tax text file and PDF.
CREATE TABLE IF NOT EXISTS companies (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_en TEXT, name_th TEXT, address_en TEXT, address_th TEXT,
    tax_info TEXT, tax_no TEXT, phone TEXT, fax TEXT, email TEXT, website TEXT, image TEXT,
    tax_id VARCHAR(20), branch_id VARCHAR(10) NOT NULL DEFAULT '00000',
    user_code TEXT, access_key TEXT, service_code TEXT, api_key TEXT, field_type TEXT,
    payment_note_en TEXT, payment_note_th TEXT, receipt_note_en TEXT, receipt_note_th TEXT,
    credit_note_en TEXT, credit_note_th TEXT, batch_text_en TEXT, batch_text_th TEXT, footer_text_en TEXT, footer_text_th TEXT,
    is_primary      BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- What happened to each e-tax document
ALTER TABLE inets ADD COLUMN IF NOT EXISTS auto_pdf BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE inets ADD COLUMN IF NOT EXISTS message_388 TEXT;
ALTER TABLE inets ADD COLUMN IF NOT EXISTS message_t01 TEXT;
ALTER TABLE inets ADD COLUMN IF NOT EXISTS message_81  TEXT;
ALTER TABLE inets ADD COLUMN IF NOT EXISTS modify_388_by BIGINT;
ALTER TABLE inets ADD COLUMN IF NOT EXISTS modify_t01_by BIGINT;
ALTER TABLE inets ADD COLUMN IF NOT EXISTS modify_81_by  BIGINT;
ALTER TABLE inets ADD COLUMN IF NOT EXISTS reference_invoice TEXT;
