-- Billing notes (ใบวางบิล): our own data, not an ERP copy.
CREATE TABLE IF NOT EXISTS billing_notes (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    billing_number  VARCHAR(40) NOT NULL UNIQUE,
    is_thai         BOOLEAN NOT NULL DEFAULT TRUE,
    customer_id     BIGINT,
    customer_code   TEXT,
    customer_name   TEXT,
    vat_number      TEXT,
    address         TEXT,
    total_amount    NUMERIC(24,2) NOT NULL DEFAULT 0,
    currency_code   VARCHAR(8) NOT NULL DEFAULT 'THB',
    note            TEXT,
    remark          TEXT,
    billing_at      DATE NOT NULL DEFAULT CURRENT_DATE,
    remind_date     DATE,
    notify_time     VARCHAR(5),
    is_paid         BOOLEAN NOT NULL DEFAULT FALSE,
    is_complete     BOOLEAN NOT NULL DEFAULT FALSE,
    approved_by     BIGINT,
    file_key        TEXT,
    notified_on     DATE,
    created_by      BIGINT,
    updated_by      BIGINT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS billing_notes_remind_idx ON billing_notes (remind_date);
CREATE INDEX IF NOT EXISTS billing_notes_customer_idx ON billing_notes (customer_id);

CREATE TABLE IF NOT EXISTS billing_note_invoices (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    billing_id      BIGINT NOT NULL REFERENCES billing_notes(id) ON DELETE CASCADE,
    invoice_number  BIGINT NOT NULL,
    order_no        TEXT,
    amount          NUMERIC(24,2) NOT NULL DEFAULT 0,
    vat_amount      NUMERIC(24,2) NOT NULL DEFAULT 0,
    is_credit       BOOLEAN NOT NULL DEFAULT FALSE,
    invoice_date    DATE,
    due_date        DATE
);
CREATE INDEX IF NOT EXISTS billing_note_invoices_billing_idx ON billing_note_invoices (billing_id);
CREATE INDEX IF NOT EXISTS billing_note_invoices_invoice_idx ON billing_note_invoices (invoice_number);
CREATE INDEX IF NOT EXISTS erp_invoices_invoice_date_idx ON erp_invoices (invoice_date);
CREATE INDEX IF NOT EXISTS erp_documents_customer_idx ON erp_documents (customer_id);
