-- =====================================================================
--  account_db  —  Accounting module
-- =====================================================================
CREATE TABLE IF NOT EXISTS accounts (                     -- chart of accounts
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code       VARCHAR(20) NOT NULL UNIQUE,
    name       VARCHAR(160) NOT NULL,
    type       VARCHAR(20) NOT NULL CHECK (type IN ('asset','liability','equity','income','expense')),
    parent_id  BIGINT REFERENCES accounts(id) ON DELETE SET NULL,
    is_active  BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS invoices (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number        VARCHAR(30) NOT NULL UNIQUE,
    customer_id   BIGINT,                                 -- crm_db.customers.id
    customer_name VARCHAR(160) NOT NULL,
    issue_date    DATE NOT NULL,
    due_date      DATE,
    currency      CHAR(3) NOT NULL DEFAULT 'THB',
    subtotal      NUMERIC(14,2) NOT NULL DEFAULT 0,
    tax_total     NUMERIC(14,2) NOT NULL DEFAULT 0,
    total         NUMERIC(14,2) NOT NULL DEFAULT 0,
    amount_paid   NUMERIC(14,2) NOT NULL DEFAULT 0,
    status        VARCHAR(20) NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','sent','partial','paid','void')),
    notes         TEXT,
    department_id BIGINT,
    created_by    BIGINT,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at    TIMESTAMPTZ
);
CREATE TABLE IF NOT EXISTS invoice_items (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id  BIGINT NOT NULL REFERENCES invoices(id) ON DELETE CASCADE,
    description VARCHAR(255) NOT NULL,
    quantity    NUMERIC(12,3) NOT NULL DEFAULT 1,
    unit_price  NUMERIC(14,2) NOT NULL DEFAULT 0,
    tax_rate    NUMERIC(5,2)  NOT NULL DEFAULT 7,
    line_total  NUMERIC(14,2) NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS payments (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id  BIGINT REFERENCES invoices(id) ON DELETE SET NULL,
    paid_at     DATE NOT NULL,
    amount      NUMERIC(14,2) NOT NULL,
    method      VARCHAR(20) NOT NULL DEFAULT 'bank' CHECK (method IN ('cash','bank','card','cheque','other')),
    reference   VARCHAR(80),
    account_id  BIGINT REFERENCES accounts(id) ON DELETE SET NULL,
    created_by  BIGINT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS expenses (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    spent_at      DATE NOT NULL,
    category      VARCHAR(60) NOT NULL,
    description   VARCHAR(255),
    amount        NUMERIC(14,2) NOT NULL,
    account_id    BIGINT REFERENCES accounts(id) ON DELETE SET NULL,
    receipt_path  VARCHAR(255),
    status        VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','approved','rejected','paid')),
    submitted_by  BIGINT,
    approved_by   BIGINT,
    department_id BIGINT,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS journal_entries (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_date  DATE NOT NULL,
    reference   VARCHAR(60),
    memo        VARCHAR(255),
    posted      BOOLEAN NOT NULL DEFAULT FALSE,
    created_by  BIGINT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS journal_lines (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    journal_entry_id BIGINT NOT NULL REFERENCES journal_entries(id) ON DELETE CASCADE,
    account_id       BIGINT NOT NULL REFERENCES accounts(id),
    debit            NUMERIC(14,2) NOT NULL DEFAULT 0,
    credit           NUMERIC(14,2) NOT NULL DEFAULT 0,
    memo             VARCHAR(255)
);
