-- =====================================================================
--  hr_db  —  HR module (user_id = user_db.users.id)
-- =====================================================================
CREATE TABLE IF NOT EXISTS leave_types (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(80) NOT NULL UNIQUE,
    days_per_year NUMERIC(5,1) NOT NULL DEFAULT 0,
    is_paid     BOOLEAN NOT NULL DEFAULT TRUE
);
CREATE TABLE IF NOT EXISTS leave_requests (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT NOT NULL,
    leave_type_id BIGINT NOT NULL REFERENCES leave_types(id),
    start_date    DATE NOT NULL,
    end_date      DATE NOT NULL,
    days          NUMERIC(5,1) NOT NULL,
    reason        TEXT,
    status        VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','approved','rejected','cancelled')),
    approved_by   BIGINT,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS attendance (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL,
    work_date  DATE NOT NULL,
    check_in   TIMESTAMPTZ,
    check_out  TIMESTAMPTZ,
    status     VARCHAR(20) NOT NULL DEFAULT 'present' CHECK (status IN ('present','late','absent','leave','holiday')),
    UNIQUE (user_id, work_date)
);
CREATE TABLE IF NOT EXISTS employee_documents (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT NOT NULL,
    title       VARCHAR(160) NOT NULL,
    file_path   VARCHAR(255) NOT NULL,
    expires_at  DATE,
    uploaded_by BIGINT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
INSERT INTO leave_types (name, days_per_year, is_paid) VALUES
    ('Annual leave', 14, TRUE), ('Sick leave', 30, TRUE), ('Personal leave', 3, TRUE), ('Unpaid leave', 0, FALSE)
ON CONFLICT (name) DO NOTHING;
