-- =====================================================================
--  machine_db  —  Machines, checklists, inspections, maintenance
-- =====================================================================
CREATE TABLE IF NOT EXISTS machines (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code          VARCHAR(30) NOT NULL UNIQUE,
    name          VARCHAR(160) NOT NULL,
    model         VARCHAR(80),
    serial_number VARCHAR(80),
    location      VARCHAR(120),
    department_id BIGINT,
    status        VARCHAR(20) NOT NULL DEFAULT 'running' CHECK (status IN ('running','idle','maintenance','broken','retired')),
    installed_at  DATE,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at    TIMESTAMPTZ
);
CREATE TABLE IF NOT EXISTS checklists (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(160) NOT NULL,
    frequency   VARCHAR(20) NOT NULL DEFAULT 'daily' CHECK (frequency IN ('daily','weekly','monthly','quarterly','yearly')),
    machine_id  BIGINT REFERENCES machines(id) ON DELETE CASCADE,  -- NULL = template for any machine
    is_active   BOOLEAN NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS checklist_items (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    checklist_id BIGINT NOT NULL REFERENCES checklists(id) ON DELETE CASCADE,
    question     VARCHAR(255) NOT NULL,
    answer_type  VARCHAR(20) NOT NULL DEFAULT 'pass_fail' CHECK (answer_type IN ('pass_fail','number','text')),
    sort         SMALLINT NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS inspections (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    machine_id   BIGINT NOT NULL REFERENCES machines(id) ON DELETE CASCADE,
    checklist_id BIGINT REFERENCES checklists(id) ON DELETE SET NULL,
    inspected_by BIGINT,
    inspected_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    result       VARCHAR(20) NOT NULL DEFAULT 'pass' CHECK (result IN ('pass','fail','attention')),
    notes        TEXT
);
CREATE TABLE IF NOT EXISTS inspection_answers (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inspection_id     BIGINT NOT NULL REFERENCES inspections(id) ON DELETE CASCADE,
    checklist_item_id BIGINT REFERENCES checklist_items(id) ON DELETE SET NULL,
    answer            VARCHAR(255),
    passed            BOOLEAN
);
CREATE TABLE IF NOT EXISTS maintenance (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    machine_id   BIGINT NOT NULL REFERENCES machines(id) ON DELETE CASCADE,
    type         VARCHAR(20) NOT NULL DEFAULT 'preventive' CHECK (type IN ('preventive','corrective','breakdown')),
    title        VARCHAR(160) NOT NULL,
    description  TEXT,
    scheduled_at DATE,
    completed_at TIMESTAMPTZ,
    cost         NUMERIC(14,2) NOT NULL DEFAULT 0,
    technician_id BIGINT,
    status       VARCHAR(20) NOT NULL DEFAULT 'planned' CHECK (status IN ('planned','in_progress','done','cancelled')),
    created_by   BIGINT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
