-- =====================================================================
--  user_db  —  CORE: people, roles, permissions, work, security, logs
-- =====================================================================

CREATE TABLE IF NOT EXISTS settings (
    key         VARCHAR(100) PRIMARY KEY,
    value       TEXT,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS roles (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(80)  NOT NULL,
    slug        VARCHAR(40)  NOT NULL UNIQUE,
    description VARCHAR(255),
    level       SMALLINT     NOT NULL DEFAULT 10,          -- higher = more senior
    data_scope  VARCHAR(20)  NOT NULL DEFAULT 'own'
                CHECK (data_scope IN ('all','department','team','own')),
    is_system   BOOLEAN      NOT NULL DEFAULT FALSE,       -- built-in roles cannot be deleted
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- One row per thing you can grant access to ("members", later "crm.customers")
CREATE TABLE IF NOT EXISTS permissions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module      VARCHAR(40)  NOT NULL DEFAULT 'core',
    key         VARCHAR(80)  NOT NULL UNIQUE,
    label       VARCHAR(120) NOT NULL,
    sort        SMALLINT     NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS role_permissions (
    role_id       BIGINT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    permission_id BIGINT NOT NULL REFERENCES permissions(id) ON DELETE CASCADE,
    can_view      BOOLEAN NOT NULL DEFAULT FALSE,
    can_create    BOOLEAN NOT NULL DEFAULT FALSE,
    can_edit      BOOLEAN NOT NULL DEFAULT FALSE,
    can_delete    BOOLEAN NOT NULL DEFAULT FALSE,
    can_import    BOOLEAN NOT NULL DEFAULT FALSE,
    can_export    BOOLEAN NOT NULL DEFAULT FALSE,
    can_download  BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE IF NOT EXISTS departments (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(120) NOT NULL,
    code        VARCHAR(20)  NOT NULL UNIQUE,
    description TEXT,
    head_id     BIGINT,                                   -- BU manager (FK below)
    is_active   BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    deleted_at  TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS teams (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id BIGINT NOT NULL REFERENCES departments(id) ON DELETE CASCADE,
    name          VARCHAR(120) NOT NULL,
    description   TEXT,
    lead_id       BIGINT,                                 -- manager (FK below)
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at    TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(120) NOT NULL,
    email           VARCHAR(190) NOT NULL,
    password        VARCHAR(255) NOT NULL,
    role_id         BIGINT NOT NULL REFERENCES roles(id) ON DELETE RESTRICT,
    department_id   BIGINT REFERENCES departments(id) ON DELETE SET NULL,
    team_id         BIGINT REFERENCES teams(id) ON DELETE SET NULL,
    manager_id      BIGINT REFERENCES users(id) ON DELETE SET NULL,
    data_scope      VARCHAR(20) CHECK (data_scope IN ('all','department','team','own')),  -- NULL = use role scope
    avatar          VARCHAR(255),
    is_active       BOOLEAN     NOT NULL DEFAULT TRUE,
    session_version INTEGER     NOT NULL DEFAULT 1,       -- bump to sign out every device
    last_login_at   TIMESTAMPTZ,
    last_login_ip   VARCHAR(45),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at      TIMESTAMPTZ
);
CREATE UNIQUE INDEX IF NOT EXISTS users_email_unique ON users (lower(email));
CREATE INDEX IF NOT EXISTS users_department_idx ON users (department_id);
CREATE INDEX IF NOT EXISTS users_team_idx ON users (team_id);

DO $$ BEGIN
    ALTER TABLE departments ADD CONSTRAINT departments_head_fk FOREIGN KEY (head_id) REFERENCES users(id) ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
    ALTER TABLE teams ADD CONSTRAINT teams_lead_fk FOREIGN KEY (lead_id) REFERENCES users(id) ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS employee_profiles (
    user_id                 BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    employee_code           VARCHAR(30) UNIQUE,
    job_title               VARCHAR(120),
    phone                   VARCHAR(30),
    date_of_birth           DATE,
    joined_at               DATE,
    address                 VARCHAR(255),
    emergency_contact_name  VARCHAR(120),
    emergency_contact_phone VARCHAR(30),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Per-member overrides. NULL = inherit from role.
CREATE TABLE IF NOT EXISTS user_permissions (
    user_id       BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    permission_id BIGINT NOT NULL REFERENCES permissions(id) ON DELETE CASCADE,
    can_view      BOOLEAN,
    can_create    BOOLEAN,
    can_edit      BOOLEAN,
    can_delete    BOOLEAN,
    can_import    BOOLEAN,
    can_export    BOOLEAN,
    can_download  BOOLEAN,
    PRIMARY KEY (user_id, permission_id)
);

-- "Remember me" (selector + hashed validator, one row per device)
CREATE TABLE IF NOT EXISTS remember_tokens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    selector    VARCHAR(32) NOT NULL UNIQUE,
    token_hash  VARCHAR(64) NOT NULL,
    user_agent  VARCHAR(255),
    expires_at  TIMESTAMPTZ NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS password_resets (
    email       VARCHAR(190) PRIMARY KEY,
    token_hash  VARCHAR(64)  NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS login_attempts (
    key          VARCHAR(255) PRIMARY KEY,                -- email|ip
    attempts     SMALLINT    NOT NULL DEFAULT 0,
    locked_until TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS passkeys (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name          VARCHAR(80)  NOT NULL,
    credential_id VARCHAR(512) NOT NULL UNIQUE,          -- base64url
    public_key    TEXT         NOT NULL,                 -- PEM
    algorithm     SMALLINT     NOT NULL,                 -- -7 ES256, -8 EdDSA, -257 RS256
    sign_count    BIGINT       NOT NULL DEFAULT 0,
    last_used_at  TIMESTAMPTZ,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS kpis (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,   -- owner
    department_id BIGINT REFERENCES departments(id) ON DELETE SET NULL,
    team_id       BIGINT REFERENCES teams(id) ON DELETE SET NULL,
    created_by    BIGINT REFERENCES users(id) ON DELETE SET NULL,
    title         VARCHAR(160) NOT NULL,
    description   TEXT,
    unit          VARCHAR(20)  NOT NULL DEFAULT '%',
    target        NUMERIC(14,2) NOT NULL,
    actual        NUMERIC(14,2) NOT NULL DEFAULT 0,
    period_start  DATE NOT NULL,
    period_end    DATE NOT NULL,
    status        VARCHAR(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active','achieved','missed','archived')),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at    TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS tasks (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assigned_to   BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_by    BIGINT REFERENCES users(id) ON DELETE SET NULL,
    department_id BIGINT REFERENCES departments(id) ON DELETE SET NULL,
    team_id       BIGINT REFERENCES teams(id) ON DELETE SET NULL,
    title         VARCHAR(200) NOT NULL,
    description   TEXT,
    status        VARCHAR(20) NOT NULL DEFAULT 'todo' CHECK (status IN ('todo','in_progress','review','done')),
    priority      VARCHAR(10) NOT NULL DEFAULT 'medium' CHECK (priority IN ('low','medium','high','urgent')),
    due_date      DATE,
    completed_at  TIMESTAMPTZ,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at    TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS tasks_status_due_idx ON tasks (status, due_date);
CREATE INDEX IF NOT EXISTS tasks_assignee_idx ON tasks (assigned_to);

CREATE TABLE IF NOT EXISTS activity_logs (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT REFERENCES users(id) ON DELETE SET NULL,
    module        VARCHAR(40)  NOT NULL DEFAULT 'core',
    action        VARCHAR(40)  NOT NULL,                  -- created|updated|deleted|login|export|…
    subject_type  VARCHAR(40),
    subject_id    BIGINT,
    subject_label VARCHAR(255),
    description   VARCHAR(255) NOT NULL,
    properties    JSONB,
    ip_address    VARCHAR(45),
    user_agent    VARCHAR(255),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS activity_created_idx ON activity_logs (created_at DESC);
CREATE INDEX IF NOT EXISTS activity_action_idx  ON activity_logs (action);
CREATE INDEX IF NOT EXISTS activity_user_idx    ON activity_logs (user_id);
