-- "Request" on the sign-in page: somebody asks for an account. An administrator reviews it and turns it into a member.
-- The password the person chose is stored only as a hash and is used as is when the request is approved: nobody ever sees it.
CREATE TABLE IF NOT EXISTS access_requests (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_code   VARCHAR(30)  NOT NULL,
    name            VARCHAR(120) NOT NULL,
    email           VARCHAR(190) NOT NULL,
    phone           VARCHAR(30),
    gender          VARCHAR(20),
    department_text VARCHAR(120),
    password_hash   VARCHAR(255),
    status          VARCHAR(12)  NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','approved','rejected')),
    user_id         BIGINT REFERENCES users(id) ON DELETE SET NULL,
    reviewed_by     BIGINT REFERENCES users(id) ON DELETE SET NULL,
    reviewed_at     TIMESTAMPTZ,
    reject_reason   VARCHAR(300),
    ip_address      VARCHAR(45),
    locale          VARCHAR(5),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS access_requests_status_idx ON access_requests (status, created_at DESC);
CREATE INDEX IF NOT EXISTS access_requests_email_idx ON access_requests (lower(email));
