-- In-app notifications (the bell), plus CRM permissions for stages and sales targets.
CREATE TABLE IF NOT EXISTS notifications (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    module     VARCHAR(40)  NOT NULL DEFAULT 'core',
    type       VARCHAR(40)  NOT NULL,                 -- commented | reminder | shared | updated …
    title      VARCHAR(200) NOT NULL,
    body       VARCHAR(500),
    url        VARCHAR(255),
    actor_id   BIGINT REFERENCES users(id) ON DELETE SET NULL,
    read_at    TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS notifications_user_idx ON notifications (user_id, read_at, created_at DESC);

-- New permission rows (on a brand-new install user_db_seed.sql adds them instead).
INSERT INTO permissions (module, key, label, sort)
SELECT 'crm', k, l, s FROM (VALUES
  ('crm_stages',  'CRM opportunity stages', 170),
  ('crm_targets', 'CRM sales targets',      180)
) AS v(k, l, s)
WHERE EXISTS (SELECT 1 FROM roles)
ON CONFLICT (key) DO NOTHING;

-- Letters: v=view c=create e=edit d=delete i=import x=export w=download
INSERT INTO role_permissions (role_id, permission_id, can_view, can_create, can_edit, can_delete, can_import, can_export, can_download)
SELECT r.id, p.id,
       position('v' IN d.l) > 0, position('c' IN d.l) > 0, position('e' IN d.l) > 0, position('d' IN d.l) > 0,
       position('i' IN d.l) > 0, position('x' IN d.l) > 0, position('w' IN d.l) > 0
FROM (VALUES
  ('admin','crm_stages','vcedixw'),('admin','crm_targets','vcedixw'),
  ('management','crm_stages',''),('management','crm_targets','v'),
  ('bu_manager','crm_stages','ve'),('bu_manager','crm_targets','vce'),
  ('manager','crm_stages',''),('manager','crm_targets','v'),
  ('member','crm_stages',''),('member','crm_targets','')
) AS d(role, perm, l)
JOIN roles r ON r.slug = d.role
JOIN permissions p ON p.key = d.perm
ON CONFLICT (role_id, permission_id) DO NOTHING;

-- CRM settings (industries, lead sources, products, currencies): only BU Managers and Managers (and Admin).
UPDATE role_permissions rp SET can_view = FALSE, can_create = FALSE, can_edit = FALSE, can_delete = FALSE, can_import = FALSE, can_export = FALSE, can_download = FALSE
  FROM roles r, permissions p
 WHERE rp.role_id = r.id AND rp.permission_id = p.id AND p.key = 'crm_settings' AND r.slug IN ('management', 'member');
UPDATE role_permissions rp SET can_view = TRUE, can_create = TRUE, can_edit = TRUE, can_delete = TRUE, can_export = TRUE
  FROM roles r, permissions p
 WHERE rp.role_id = r.id AND rp.permission_id = p.id AND p.key = 'crm_settings' AND r.slug = 'manager';
