-- Server-side register of every signed-in browser: lets the person (or an administrator) see and end sessions,
-- rotates the session id every few minutes and ends every session after a hard maximum (see config security.*).
CREATE TABLE IF NOT EXISTS user_sessions (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    session_hash      CHAR(64) NOT NULL,              -- sha256 of the PHP session id (the id itself is never stored)
    prev_hash         CHAR(64),                       -- the id before the last rotation, accepted for a short grace period
    prev_until        TIMESTAMPTZ,
    method            VARCHAR(30),
    ip                VARCHAR(64),
    user_agent        VARCHAR(255),
    device            VARCHAR(120),
    remember_selector VARCHAR(32),
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    rotated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at        TIMESTAMPTZ NOT NULL,
    revoked_at        TIMESTAMPTZ,
    revoked_by        BIGINT,
    revoke_reason     VARCHAR(30)
);
CREATE INDEX IF NOT EXISTS user_sessions_hash_idx ON user_sessions (session_hash);
CREATE INDEX IF NOT EXISTS user_sessions_prev_idx ON user_sessions (prev_hash);
CREATE INDEX IF NOT EXISTS user_sessions_user_idx ON user_sessions (user_id, revoked_at);

-- Device log: who signed in / out / failed / was signed out, from where.
CREATE TABLE IF NOT EXISTS login_events (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT REFERENCES users(id) ON DELETE CASCADE,
    email       VARCHAR(190),
    event       VARCHAR(20) NOT NULL,                 -- login | logout | failed | revoked | expired
    method      VARCHAR(30),
    ip          VARCHAR(64),
    user_agent  VARCHAR(255),
    device      VARCHAR(120),
    note        VARCHAR(190),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS login_events_user_idx ON login_events (user_id, created_at DESC);

ALTER TABLE remember_tokens ADD COLUMN IF NOT EXISTS started_at TIMESTAMPTZ;
