-- What happened to every e-mail the system tried to send (so a silent SMTP problem is visible).
CREATE TABLE IF NOT EXISTS mail_log (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    to_email   VARCHAR(190) NOT NULL,
    subject    VARCHAR(255) NOT NULL,
    driver     VARCHAR(10)  NOT NULL,
    status     VARCHAR(10)  NOT NULL,                 -- sent | failed
    error      TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS mail_log_created_idx ON mail_log (created_at DESC);
