<?php
/*
 | Each module has its own sidebar, dashboards and notification switches.
 | The module comes from the first URL segment (/crm, /accounting …); anything else is "core".
 | Menu items show only when the user holds the permission ("resource.action").
 | Dashboards: people can pick one as their default in Preferences.
 */
return [
    'core' => [
        'name' => 'User Management', 'icon' => 'users', 'home' => '/dashboard', 'enabled' => true, 'db' => 'core',
        'dashboards' => [
            'personal' => ['label' => 'My workspace', 'url' => '/dashboard/personal'],
            'admin'    => ['label' => 'Control room', 'url' => '/dashboard/admin', 'admin_only' => true],
        ],
        'menu' => [
            ['heading' => 'Overview'],
            ['label' => 'Control room',     'url' => '/dashboard/admin',    'icon' => 'chart', 'admin_only' => true],
            ['label' => 'My workspace',     'url' => '/dashboard/personal', 'icon' => 'home'],
            ['heading' => 'Work'],
            ['label' => 'Calendar',         'url' => '/calendar',    'icon' => 'calendar'],
            ['label' => 'Mail',             'url' => '/mail',        'icon' => 'mail'],
            ['label' => 'Tasks',            'url' => '/tasks',       'icon' => 'check',    'permission' => 'tasks.view'],
            ['label' => 'KPIs',             'url' => '/kpis',        'icon' => 'target',   'permission' => 'kpis.view'],
            ['heading' => 'Organization'],
            ['label' => 'Members',          'url' => '/members',     'icon' => 'users',    'permission' => 'members.view'],
            ['label' => 'Departments',      'url' => '/departments', 'icon' => 'building', 'permission' => 'departments.view'],
            ['label' => 'Teams',            'url' => '/teams',       'icon' => 'team',     'permission' => 'teams.view'],
            ['heading' => 'Administration'],
            ['label' => 'Roles & access',   'url' => '/roles',       'icon' => 'shield',   'permission' => 'roles.view'],
            ['label' => 'Activity log',     'url' => '/activity',    'icon' => 'clock',    'permission' => 'activity_logs.view'],
            ['label' => 'Sessions',         'url' => '/sessions',    'icon' => 'lock',     'admin_only' => true],
            ['label' => 'Connectors',       'url' => '/connectors',  'icon' => 'link',     'admin_only' => true],
            ['label' => 'File manager',     'url' => '/files',       'icon' => 'folder',   'admin_only' => true],
            ['label' => 'Company settings', 'url' => '/settings',    'icon' => 'cog',      'permission' => 'settings.view'],
        ],
    ],
    // Switch "enabled" on when a module is built. Their databases already exist.
    'crm' => [
        'name' => 'CRM', 'icon' => 'handshake', 'home' => '/crm', 'enabled' => true, 'db' => 'crm',
        'dashboards' => [
            'overview' => ['label' => 'CRM overview', 'url' => '/crm/dashboard'],
        ],
        'menu' => [
            ['heading' => 'Overview'],
            ['label' => 'CRM overview',  'url' => '/crm/dashboard',     'icon' => 'chart',     'permission' => 'crm_dashboard.view'],
            ['heading' => 'Sales'],
            ['label' => 'Leads',         'url' => '/crm/leads',         'icon' => 'building',  'permission' => 'crm_leads.view'],
            ['label' => 'Contacts',      'url' => '/crm/contacts',      'icon' => 'user',      'permission' => 'crm_contacts.view'],
            ['label' => 'Opportunities', 'url' => '/crm/opportunities', 'icon' => 'target',    'permission' => 'crm_opportunities.view'],
            ['label' => 'Pipeline',      'url' => '/crm/pipeline',      'icon' => 'columns',   'permission' => 'crm_opportunities.view'],
            ['label' => 'Activities',    'url' => '/crm/activities',    'icon' => 'clock',     'permission' => 'crm_activities.view'],
            ['label' => 'Calendar',      'url' => '/crm/calendar',      'icon' => 'calendar',  'permission' => 'crm_activities.view'],
            ['heading' => 'Work'],
            ['label' => 'Projects',      'url' => '/crm/projects',      'icon' => 'folder',    'permission' => 'crm_projects.view'],
            ['label' => 'Tasks',         'url' => '/crm/tasks',         'icon' => 'tasks',     'permission' => 'crm_tasks.view'],
            ['label' => 'Team',          'url' => '/crm/team',          'icon' => 'users',     'permission' => 'crm_reassign.view'],
            ['heading' => 'Marketing'],
            ['label' => 'Campaigns',     'url' => '/crm/campaigns',     'icon' => 'chat',      'permission' => 'crm_campaigns.view'],
            ['heading' => 'Setup'],
            ['label' => 'Data tools',    'url' => '/crm/data',          'icon' => 'download',  'admin_only' => true],
            ['label' => 'Industries',    'url' => '/crm/settings/industries',   'icon' => 'building', 'permission' => 'crm_settings.view'],
            ['label' => 'Lead sources',  'url' => '/crm/settings/lead-sources', 'icon' => 'globe',    'permission' => 'crm_settings.view'],
        ],
    ],
    'accounting' => [
        'name' => 'Accounting', 'icon' => 'calc', 'home' => '/accounting', 'enabled' => true, 'db' => 'accounting',
        'dashboards' => ['overview' => ['label' => 'Accounting overview', 'url' => '/accounting']],
        'menu' => [
            ['heading' => 'Overview'],
            ['label' => 'Accounting overview', 'url' => '/accounting', 'icon' => 'chart'],
            ['heading' => 'ERP data'],
            ['label' => 'Customers', 'url' => '/accounting/customers', 'icon' => 'users', 'permission' => 'accounting_customers.view'],
            ['label' => 'Orders',    'url' => '/accounting/orders',    'icon' => 'cart',  'permission' => 'accounting_orders.view'],
            ['label' => 'Invoices',  'url' => '/accounting/invoices',  'icon' => 'doc',   'permission' => 'accounting_invoices.view'],
            ['label' => 'Products',  'url' => '/accounting/products',  'icon' => 'box',   'permission' => 'accounting_products.view'],
            ['label' => 'Sellers',   'url' => '/accounting/sellers',   'icon' => 'users', 'permission' => 'accounting_sellers.view'],
            ['heading' => 'E-Tax'],
            ['label' => 'Inets',     'url' => '/accounting/inet',      'icon' => 'doc',   'permission' => 'accounting_inet.view'],
            ['heading' => 'Billing'],
            ['label' => 'Billing notes', 'url' => '/accounting/billing', 'icon' => 'doc', 'permission' => 'accounting_billing.view'],
            ['heading' => 'Setup'],
            ['label' => 'Company',        'url' => '/accounting/company', 'icon' => 'building', 'admin_only' => true],
            ['label' => 'Notifications',  'url' => '/accounting/notify', 'icon' => 'bell', 'admin_only' => true],
            ['label' => 'ERP connection', 'url' => '/accounting/erp', 'icon' => 'cog', 'admin_only' => true],
            ['label' => 'Logs',           'url' => '/accounting/logs', 'icon' => 'tasks', 'admin_only' => true],
        ],
    ],
    'inventory'  => ['name' => 'Inventory',  'icon' => 'box',       'home' => '/inventory',  'enabled' => false, 'db' => 'inventory',  'dashboards' => [], 'menu' => []],
    'machines' => [
        'name' => 'Machine Checklist', 'icon' => 'gear', 'home' => '/machines', 'enabled' => true, 'db' => 'machines',
        'dashboards' => [],
        'menu' => [
            ['heading' => 'Daily work'],
            ['label' => 'Scan QR code',   'url' => '/machines/scan',        'icon' => 'qr'],
            ['label' => 'Checklists',     'url' => '/machines/checklists',  'icon' => 'check',   'permission' => 'machines_checklists.view'],
            ['heading' => 'Machines'],
            ['label' => 'Machines',       'url' => '/machines/machines',    'icon' => 'gear',    'permission' => 'machines_machines.view'],
            ['label' => 'Register',       'url' => '/machines/register',    'icon' => 'doc',     'permission' => 'machines_register.view'],
            ['label' => 'Maintenance',    'url' => '/machines/maintenance', 'icon' => 'tools',   'permission' => 'machines_maintenance.view'],
            ['label' => 'Calibration',    'url' => '/machines/calibration', 'icon' => 'target',  'permission' => 'machines_calibration.view'],
            ['heading' => 'Setup'],
            ['label' => 'Machine types',  'url' => '/machines/types',       'icon' => 'columns', 'permission' => 'machines_types.view'],
            ['label' => 'Questions',      'url' => '/machines/questions',   'icon' => 'list',    'permission' => 'machines_questions.view'],
        ],
    ],
    'hr'         => ['name' => 'HR',         'icon' => 'id',        'home' => '/hr',         'enabled' => false, 'db' => 'hr',         'dashboards' => [], 'menu' => []],
];
